apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  name: app
spec:
  license:
    accept: true
    edition: IBM WebSphere Application Server
    productEntitlementSource: Standalone
  replicas: {{ .Values.app.instances }}
  applicationImage: {{ .Values.repository }}:{{ .Values.app.version }}
